"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta # ⭐️ Import สำหรับ SIMPLE_JWT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-0nzfenix*td&-fdsb5h_n%4k&e6krw%d4=gpyl-lb%o0ui3k0d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# 1. INSTALLED_APPS
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',          
    'drf_spectacular',   
    
    # Local apps
    'api.apps.ApiConfig', 
]

# 2. MIDDLEWARE
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# 3. Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# 4. Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 5. Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# 6. Static files
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- 7. การตั้งค่า REST FRAMEWORK (รวมทุกอย่างไว้ที่นี่) ---
REST_FRAMEWORK = {
    # 7.1 ระบบยืนยันตัวตน (Authentication)
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    # 7.2 ระบบสิทธิ์ (Permission)
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', 
    ),
    
    # 7.3 ตั้งค่าสำหรับ API Docs (Spectacular)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # 7.4 ตั้งค่าสำหรับ Pagination (ถ้ามี)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}


# --- 8. การตั้งค่า SIMPLE JWT (รวมทุกอย่างไว้ที่นี่) ---
SIMPLE_JWT = {
    # 8.1 กำหนดอายุ Token
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # 8.2 ⭐️ [แก้ไขปัญหา Postman] ให้รองรับ Header แบบ 'Bearer' และ 'JWT'
    'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
}


# --- 9. การตั้งค่าสำหรับ Swagger/Spectacular ---
SPECTACULAR_SETTINGS = {
    'TITLE': 'ระบบคำร้องออนไลน์ (Student Request API)',
    'DESCRIPTION': 'API สำหรับระบบยื่นคำร้องออนไลน์ในองค์กร (โครงงานประจำวิชา)',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, 
}


# --- 10. การตั้งค่า CORS (ถูกต้องแล้ว) ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", 
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True


# --- 11. การตั้งค่า Media (ถูกต้องแล้ว) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'